"""обновление: удалена строка payload из Notification; строка channel заменена на channels, а её тип на ARRAY

Revision ID: 126c43960b06
Revises: 2c8fa6ec251d
Create Date: 2026-01-07 11:48:25.547191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '126c43960b06'
down_revision: Union[str, None] = '2c8fa6ec251d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('channels', sa.ARRAY(sa.String()), nullable=False))
    op.drop_column('notifications', 'payload')
    op.drop_column('notifications', 'channel')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('channel', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('notifications', 'channels')
    # ### end Alembic commands ###
