"""добавление: добавлено поле recipient с типом ARRAY(String)

Revision ID: eeb8cd31567e
Revises: 126c43960b06
Create Date: 2026-02-03 16:16:48.683506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeb8cd31567e'
down_revision: Union[str, None] = '126c43960b06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('recipient', sa.ARRAY(sa.String()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'recipient')
    # ### end Alembic commands ###
